export const  corRodape = "#4e4d0a"
export const  corSecundaria = "#FFFFFF"
export const  backgroundColor = "#87850f"
export const  font = "'Montserrat', sans-serif;"
export const  fontSecundaria = "'Josefin Sans', sans-serif;"
