export const  corPrimaria = ""
export const  corSecundaria = ""
export const  backgroundColor = "#87850f"
export const  font = "'Montserrat', sans-serif;"
export const  fontSecundaria = "'Josefin Sans', sans-serif;"
